Add async support for diff
Infomaniak/DragDropSwipeRecyclerview pull request #3
Opened 2024-06-20 08:12 UTC by TommyDL-Infomaniak

Depends on #1 
Depends on #2

2024-06-21 11:05 UTC, sirambd submitted a review, later dismissed

2024-06-21 11:05 UTC, sirambd commented on drag-drop-swipe-recyclerview/src/main/java/com/ernestoyaquello/dragdropswiperecyclerview/DragDropSwipeAdapter.kt
> +abstract class DragDropSwipeAdapter<T : Any, U : DragDropSwipeAdapter.ViewHolder>(
I think that the `Any` isn useless

2024-07-02 08:20 UTC, KevinBoulongne requested changes

2024-07-02 08:20 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview/src/main/java/com/ernestoyaquello/dragdropswiperecyclerview/util/DragDropSwipeTouchHelper.kt
> +    private val mOrientation: DragDropSwipeRecyclerView.ListOrientation
Revert this.

2024-07-02 08:20 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview/src/main/java/com/ernestoyaquello/dragdropswiperecyclerview/util/DragDropSwipeTouchHelper.kt
> -import com.ernestoyaquello.dragdropswiperecyclerview.DragDropSwipeRecyclerView.ListOrientation
Revert this.

2024-07-16 08:18 UTC, KevinBoulongne approved these changes

2024-08-20 08:27 UTC, sirambd approved these changes

2024-08-20 08:29 UTC, merged