Change publisher
Infomaniak/DragDropSwipeRecyclerview pull request #5
Opened 2024-06-27 06:28 UTC by TommyDL-Infomaniak

2024-06-27 06:47 UTC, TommyDL-Infomaniak commented
The duplication of new code appears in the sample, it can be ignored.

2024-07-16 08:31 UTC, KevinBoulongne requested changes

2024-07-16 08:31 UTC, KevinBoulongne commented on README.md
> +        position: Int
```suggestion
        position: Int,
```

2024-07-16 08:31 UTC, KevinBoulongne commented on README.md
> +        item: String
```suggestion
        item: String,
```

2024-07-16 08:31 UTC, KevinBoulongne commented on README.md
> +        distance: Int
```suggestion
        distance: Int,
```

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/MainActivity.kt
> +package com.github.infomaniak.dragdropswiperecyclerviewsample
Remove the `.github` in all packages.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/build.gradle
> +        applicationId "com.github.infomaniak.dragdropswiperecyclerviewsample"
Remove the `.github` in the applicationId.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/build.gradle
> +    namespace 'com.github.infomaniak.dragdropswiperecyclerviewsample'
Remove the `.github` in the namespace.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview/build.gradle
> +    namespace 'com.github.infomaniak.dragdropswiperecyclerview'
Remove the `.github` in the namespace.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview/build.gradle
> +                groupId = 'com.github.infomaniak.dragdropswiperecyclerview'
```suggestion
                groupId = 'com.github.infomaniak'
```

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/feature/managelists/view/HorizontalListFragment.kt
> +                    R.layout.behind_swiped_horizontal_list_secondary
Revert ?

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/feature/managelists/view/HorizontalListFragment.kt
> +                    ContextCompat.getColor(currentContext, R.color.swipeBehindBackground)
Revert ?

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +}
Jump line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +                instance = IceCreamRepository()
One line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        Random().nextInt((endInclusive + 1) - start) + start
One line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        "${adjectives.shuffled().take(1)[0]} ${names.shuffled().take(1)[0]}"
One line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        blue: Float
```suggestion
        blue: Float,
```

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +            IceCream(iceCreamName, iceCreamPrice, enhancedRed, enhancedGreen, enhancedBlue)
One line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        "Yorkie"
```suggestion
        "Yorkie",
```

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        "Tasty"
```suggestion
        "Tasty",
```

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/model/IceCream.kt
> +}
Jump line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/config/local/AppConfig.kt
> +    get() = listFragmentConfigurations[currentListFragmentType.index]
Jump line.

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/model/IceCream.kt
> +    val colorBlue: Float
```suggestion
    val colorBlue: Float,
```

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/MainActivity.kt
> +        )
One line ?

2024-07-16 08:31 UTC, KevinBoulongne commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/MainActivity.kt
> +        )
One line ?

2024-07-16 11:34 UTC, TommyDL-Infomaniak commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/feature/managelists/view/HorizontalListFragment.kt
> +                    R.layout.behind_swiped_horizontal_list_secondary
It is too long to fit in one line.

2024-07-16 11:35 UTC, TommyDL-Infomaniak commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/feature/managelists/view/HorizontalListFragment.kt
> +                    ContextCompat.getColor(currentContext, R.color.swipeBehindBackground)
It is too long to fit on one line.

2024-07-16 11:36 UTC, TommyDL-Infomaniak commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        Random().nextInt((endInclusive + 1) - start) + start
It is too long to fit on one line.

2024-07-16 11:36 UTC, TommyDL-Infomaniak commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +        "${adjectives.shuffled().take(1)[0]} ${names.shuffled().take(1)[0]}"
It is too long to fit on one line.

2024-07-16 11:36 UTC, TommyDL-Infomaniak commented on drag-drop-swipe-recyclerview-sample/src/main/java/com/github/infomaniak/dragdropswiperecyclerviewsample/data/source/IceCreamRepository.kt
> +            IceCream(iceCreamName, iceCreamPrice, enhancedRed, enhancedGreen, enhancedBlue)
It is too long to fit on one line.

2024-07-16 12:03 UTC, KevinBoulongne approved these changes

2024-07-16 12:27 UTC, merged